pool:
  vmImage: 'VS2017-Win2016'

steps:
- script: |
    dotnet restore
    dotnet build --configuration Release
  workingDirectory: "$(System.DefaultWorkingDirectory)/PingFunction"
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'svc-sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'subhendu-de_sonarqube-demo'
    cliProjectName: 'subhendu-de_sonarqube-demo'
    cliSources: '.'
    extraProperties: 'sonar.organization=subhendu-de'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release'
    projects: '$(System.DefaultWorkingDirectory)/PingFunction/*.csproj'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'