trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'VS2017-Win2016'

steps: 
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'svc-sonarcloud'
    organization: 'subhendu-de'
    scannerMode: 'MSBuild'
    projectKey: 'subhendu-de_sonarqube-demo'
    projectName: 'subhendu-de_sonarqube-demo'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: '$(System.DefaultWorkingDirectory)/SampleWebApp/*.csproj'
    platform: 'any cpu'
    configuration: 'Release'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/get-sonarqube-quality-gate-status.ps1'
    arguments: '-SonarToken $(SonarToken) -SonarServerName sonarcloud.io -SonarProjectKey subhendu-de_sonarqube-demo -Branch dev'

