trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

steps: 
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'svc-sonarcloud'
    organization: 'subhendu-de'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'subhendu-de_sonarqube-demo'
    cliProjectName: 'subhendu-de_sonarqube-demo'
    cliSources: '.'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/SampleWebApp'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

