trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'VS2017-Win2016'

steps: 
- script: |
    dotnet restore
    dotnet build --configuration Release
    workingDirectory: "$(System.DefaultWorkingDirectory)/SampleWebApp"

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'svc-sonarcloud'
    organization: 'subhendu-de'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'subhendu-de_sonarqube-demo'
    cliProjectName: 'subhendu-de_sonarqube-demo'
    cliSources: '.'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release'
    projects: '$(System.DefaultWorkingDirectory)/SampleWebApp/*.csproj'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/get-sonarqube-quality-gate-status.ps1'
    arguments: '-SonarToken $(SonarToken) -SonarServerName sonarcloud.io -SonarProjectKey subhendu-de_sonarqube-demo -Branch dev'

