pool:
  vmImage: 'VS2017-Win2016'

steps:
- script: |
    dotnet restore
    dotnet build --configuration Release
  workingDirectory: "$(System.DefaultWorkingDirectory)/PingFunction"
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release'
    projects: '*.csproj'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    ArtifactName: 'drop'