# the pipeline triggers when ay pr is merged to the main branch
trigger:
  - main

# the pipeline triggers when pr is raised from feature branch to the main branch
pr:
  - main

pool:
  vmImage: 'windows-latest'
  demands:
    - MSBuild

steps: 
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'svc-sonarcloud'
    organization: 'subhendu-de'
    scannerMode: 'MSBuild'
    projectKey: 'subhendu-de_sonarqube-demo'
    projectName: 'subhendu-de_sonarqube-demo'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/SampleWebApp'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

# - task: PowerShell@2
#   inputs:
#     filePath: '$(System.DefaultWorkingDirectory)/get-sonarqube-quality-gate-status.ps1'
#     arguments: '-SonarToken $(SonarToken) -SonarServerName sonarcloud.io -SonarProjectKey subhendu-de_sonarqube-demo -Branch dev'

